language: node_js
node_js:
  - "8.2"
deploy:
  provider: azure_web_apps
  verbose: true
  skip_cleanup: true
   username: harricomdeployment       # If AZURE_WA_USERNAME isn't set
   password: thankyou   # If AZURE_WA_PASSWORD isn't set
   site: harricomaudit       # If AZURE_WA_SITE isn't set
  # slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set